name: Rajaspot
favicon: null
layout_spectrum: 0.3810835292097181
typography_spectrum: 0.50596
title: Rajaspot - Search.Find.Complete
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ed1b24'
    - '#00adef'
    - '#606060'
  brandStrength: 0.8543031387962401
  lightness: 0.632475875550881
  saturation: 0.20806121500208974
  rhythmicContrast: 0.9395772132556885
purpose: []
