name: Rajaspot
favicon: null
layout_spectrum: 0.3810835292097181
typography_spectrum: 0.43555258377455175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8543031387962401
  lightness: 0.632475875550881
  saturation: 0.20806121500208974
  rhythmicContrast: 0.9395772132556885
purpose: []
